---
on: [push, pull_request]
name: Test
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.21.3'

      - name: Check out code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Get full repo history
        run: git fetch --prune --unshallow --tags

      - name: Download dependencies
        shell: bash
        run: go mod download

      - name: Build
        shell: bash
        run: |
          mkdir -p bin
          go build -o bin .
          ls -la bin

      - name: Test
        shell: bash
        run: go test -race -timeout 60s ./...
